[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "advent_of_code24"
version = "0.1.0"
description = "ivi printer"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]